@startuml `Usecase

left to right direction
skinparam packageStyle rectangle

actor "Актор(зритель)" as User
actor "Актор(кассир)" as Cashier
actor "Актор(администратор)" as Admin

package "Система учета и продажи билетов" {
  usecase "войти в систему" as UC_Login2
  usecase "войти в систему" as UC_Login1
  usecase "войти в систему" as UC_Login
  usecase "купить билет" as UC_Buy
  usecase "вернуть билет" as UC_Return
  usecase "посмотреть расписание" as UC_Schedule
  usecase "посмотреть свободные места" as UC_Seats
  usecase "продать билет" as UC_Sell
  usecase "управлять залом" as UC_Stock
  usecase "управлять сеансами" as UC_Sessions
  usecase "управлять фильмами" as UC_Films
  usecase "экспортировать отчет" as UC_Export
  usecase "сформировать отчет" as UC_Report
}

User -- UC_Login
UC_Login -- UC_Return
UC_Login -- UC_Schedule
UC_Login -- UC_Seats

Cashier -- UC_Login1
UC_Login1 -- UC_Sell
UC_Login1 -- UC_Schedule
UC_Login1 -- UC_Seats

Admin -- UC_Login2
UC_Login2 -- UC_Stock
UC_Login2 -- UC_Sessions
UC_Login2 -- UC_Films
UC_Login2 -- UC_Report

UC_Seats ..> UC_Buy : Include
UC_Report ..> UC_Export : Include

@enduml
